### ISSUE TITLE
Renaming videos

### ISSUE THREAD

**Issue by a0m0rajab** [danthem/PRECsort#7]
The docs itself has some details about renaming the video files, we can use it as well beside the image files. 

https://www.cgsecurity.org/wiki/After_Using_PhotoRec

**Comment by danthem** [comment]
Thank you, yes it appears that exiftool might be a good candidate to replace exiv2 as it can dig out exif data from more files. I'm doing a recovery at the moment where exiv2 does not detect data but exiftool does (Note: Only for movie files, jpegs there's no difference). I'll play around with it a bit and see if I should replace exiv2 completely or if both are needed.

**Comment by a0m0rajab** [comment]
That's great, I have not checked it for a while, but your tool was helpful and helped me a lot, Thank you for writing it.

**Comment by danthem** [comment]
Addressed in pull request #8 , closing issue. Thank you!
